apiVersion: v1
kind: Secret
metadata:
  name: multivalue-properties
type: Opaque
stringData:
  value1: |
    dapr.spring.demo-config-secret.multivalue.v1=spring
    dapr.spring.demo-config-secret.multivalue.v2=dapr
  value2: "dapr.spring.demo-config-secret.multivalue.v3=cloud"
---
apiVersion: v1
kind: Secret
metadata:
  name: dapr.spring.demo-config-secret.singlevalue
type: Opaque
stringData:
  dapr.spring.demo-config-secret.singlevalue: "testvalue"